apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-app-deployment
  labels:
    app: books-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-app
  template:
    metadata:
      labels:
        app: books-app
    spec:
      containers:
      - name: books-app
        image: books-management-sql
        ports:
        - containerPort: 5000
